#!/usr/bin/env sh
##########################################
#
# changejackdevice
#
# By Mads Kjeldgaard
#
# A convenience script to accompany my rofi jack scripts
# 
# This changes the jack audio device and then kills and restarts pulseaudio
# with pulse bridged to jack
##########################################

# Execute jack device chooser
# Change this if you placed the rofi jack device script somewhere else
# $HOME/.scripts/rofi-jack-device

# Kill all pulse audio
if [ ! -z $(pgrep pulseaudio) ]; then
	killall pulseaudio 

	while [ ! -z $(pgrep pulseaudio) ];
	do
		echo "Waiting for pulseaudio to die..."
		sleep 1
	done

	echo "Pulseaudio has been killed."
fi

# Restart pulseaudio and bridge to jack
echo "Restarting pulseaudio and bridging to jack"
pulseaudio --start && cadence-pulse2jack
