#!/bin/bash
#
########################
# rofi-jack-device
# by Mads Kjeldgaard
#
# Start jack with the chosen audio device using the rofi menu launcher
#
# Usage: rofi-jack-device
#
########################

rofi_command="rofi -theme gruvbox-dark -hide-scrollbar -i -dmenu -p 'jackdevice'" 

kill_old_processes(){
	# Make sure jack isn't running
	if [ ! -z $(pgrep jackd) ]; then
		killall jackd & 
		THISPID=$!
		wait $THISPID
	fi

	if [ ! -z $(pgrep jackdbus) ]; then
		killall jackdbus &
		THISPID=$!
		wait $THISPID
	fi
}

make_jack_command(){
	# If there is a config file for jack, use it's contents for the jack command
	# Else a sensible default
	if [ -f "$HOME/.jackdrc" ]; then
		echo "Found .jackdrc"
		jack_command="$( cat $HOME/.jackdrc )"
	else
		echo "could not find jackdrc"
		jack_command="/usr/bin/jackd -dalsa -dhw:0 -r48000 -p1024 -n2"
	fi

	echo "Using command: $jack_command as basis"
}

choose_card(){
	# Get all available audio interfaces
	cards=$(aplay -l|grep card)

	# Rofi command for choosing card
	chosencard="$( echo "$cards" | $rofi_command -dmenu -p "")"

	# Filter out the card number and device number from the aplay entry
	cardnum="$(echo $chosencard | grep -o -E 'card [0-9]+' | grep -o -E '[0-9]+')"
	devnum="$(echo $chosencard | grep -o -E 'device [0-9]+'| grep -o -E '[0-9]+')"
}

# If something was chosen, take action
if [ ! -z "$chosencard" ]; then

	# Choose audio card
	choose_card

	# Construct a new jack command
	make_jack_command
	newjackcommand="$(echo $jack_command | sed "s/dhw\:[0-9]/dhw:$cardnum,$devnum/g")"

	kill_old_processes

	$newjackcommand

	exit 0
else
	echo "Did not choose anything. Exiting."
	exit 1
fi
